### ISSUE TITLE
getUserContacts broken

### ISSUE THREAD

**Issue by JanAhrens** [FabianBeiner/HybridAuth-XING#11]
Commit https://github.com/FabianBeiner/HybridAuth-XING/commit/054fe37ff8a3cb48069064ac23d8aa22b31a68ef introduced a tiny bug, that prevents `getUserContracts` from generating correct URLs. 

https://github.com/FabianBeiner/HybridAuth-XING/blob/054fe37ff8a3cb48069064ac23d8aa22b31a68ef/Hybrid/Providers/XING.php#L278

The path and query part of the URL don't get separated with a question-mark character. Replacing the dot with a comma, fixes the problem.

**Comment by FabianBeiner** [comment]
Fixed in https://github.com/FabianBeiner/HybridAuth-XING/commit/2b27bed2e20588502ca51f0ad980401dbac50459.

Danke, Jan.

**Comment by JanAhrens** [comment]
Wow, that was fast :smiley: Thank you, Fabian!
