### ISSUE TITLE
403 Error when authenticating

### ISSUE THREAD

**Issue by tzfrs** [FabianBeiner/HybridAuth-XING#5]
Hi,

I'm authenticating like this

    $xing = new XingWrapper();
    if ( !$xing->hybridAuth->isConnectedWith('XING') ) {
        $xing->hybridAuth->authenticate('XING', ['hauth_return_to' => '/auth_xing.php']);
    } else {
        $xingApi        = $xing->hybridAuth->authenticate('XING');
        var_dump($xingApi->getUserProfile());
    }

However, after authenticating and calling the method `getUserProfile())` I'm getting the following error

>Profile request failed! XING API returned an error: 401 Unauthorized..

Do you need more information about the implementation or is this enough?

**Comment by FabianBeiner** [comment]
Hey,
schau dir mal http://fabian-beiner.de/de/artikel/xing-api-mit-php-hybridauth-abfragen/ an, da habe ich damals ein bisschen was zum Thema geschrieben. So kann ich leider nicht helfen, da ich nicht weiß, was ihr in `XingWrapper` alles gemacht habt. 

Gruß
Fabian

**Comment by tzfrs** [comment]
Hi,

der Xing-Wrapper macht eigentlich nur folgendes

    protected $hybridAuthConfig = [
        "base_url" => Config::XING_BASE_URL,
        "providers" => array(
            "XING" => array(
                "enabled" => true,
                // go to https://dev.xing.com/applications and create an app to get a test key
                "keys"    => array("key" => Config::XING_CONSUMER_KEY, "secret" => Config::XING_CONSUMER_SECRET),
                "wrapper" => array("path" => Config::XING_PATH_TO_HYBRID, "class" => "Hybrid_Providers_XING")
            )
        )
    ];

    public function __construct($params = null)
    {
        $this->hybridAuth = new \Hybrid_Auth($this->hybridAuthConfig);
        $this->xingApi = $this->hybridAuth->setup('XING', $params);
    }

**Comment by FabianBeiner** [comment]
Ich habe HybridAuth schon ewig nicht mehr genutzt, ich kenne zum Beispiel die Methode `setup` gar nicht. ;) Was passiert, wenn du exakt dem Beispiel aus meinem alten Blog folgst?

**Comment by tzfrs** [comment]
Hi,

ist wohl gefixd. Das Problem lag wohl an XING. Die haben uns eine Berechtigung entzogen als die uns für die Production freigeschaltet haben. Dann ist natürlich klar, dass da ein 401 kommt. Ich habe XING bereits angeschrieben, mal schauen was die dazu sagen.

**Comment by FabianBeiner** [comment]
:+1:
